# Use the official Nginx image as the base
FROM nginx:latest

# Copy the static website files to the Nginx web root directory
COPY frontend /usr/share/nginx/html

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start Nginx server
# CMD ["nginx", "-g", "daemon off;"]
